'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),os=require('os'),path=require('path');
const {Store}=require('../tools/voice/store'),{Worker}=require('../tools/voice/worker');
const {validate,defaults}=require('../tools/voice/editor/config');
const {protect,restore,instructions}=require('../tools/voice/editor/format');
const {createServer}=require('../tools/voice/server');
const conn={id:'business',user:{id:777,first_name:'Админ'},is_enabled:true,rights:{can_reply:true}};
function message(extra={}){return {message_id:10,business_connection_id:'business',date:Math.floor(Date.now()/1000),chat:{id:888,type:'private'},from:{id:777},text:'сначала открой настройки потом выбери профиль',...extra};}
function fixture(t,adapters={}){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'editor-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));const store=new Store(dir,'a'.repeat(64));Object.assign(store.data.config,{botToken:'777:example-secret-token-long-enough',openaiKey:'example-openai-secret',enabled:false,ownerIds:'999'});store.data.connections.business=structuredClone(conn);const calls=[];const worker=new Worker(store,{editorFormat:async text=>'**Инструкция**\n\n'+text,telegram:async(method,body)=>{calls.push({method,body});return structuredClone(conn);},...adapters});worker.editor.configure({enabled:true,ownerIds:'777'});return {dir,store,worker,editor:worker.editor,calls};}
test('editor independently handles selected outgoing text while voice is disabled',async t=>{const f=fixture(t),before=JSON.stringify(f.store.data.config);await f.worker.ingest({update_id:1,business_message:message()});assert.equal(f.editor.data.jobs.length,1);assert.equal(f.store.data.jobs.length,0);await f.editor.process(f.editor.data.jobs[0]);assert.equal(f.editor.data.jobs[0].status,'done');assert.equal(JSON.stringify(f.store.data.config),before);const call=f.calls.find(c=>c.method==='editMessageText');assert.equal(call.body.message_id,10);assert.equal(call.body.business_connection_id,'business');assert.equal(call.body.entities[0].type,'bold');assert.ok(!f.calls.some(x=>['sendMessage','deleteBusinessMessages'].includes(x.method)));});
test('incoming, bots, forwards, commands, voice and unselected accounts are ignored',async t=>{const {worker,editor}=fixture(t);for(const patch of [{from:{id:888}},{from:{id:777,is_bot:true}},{sender_business_bot:{id:3}},{forward_origin:{}},{text:'/start'},{text:undefined,voice:{file_id:'x',duration:10}},{chat:{id:888,type:'group'}},{text:'ок'},{date:Math.floor(Date.now()/1000)-500}])await worker.ingest({update_id:1,business_message:message(patch)});assert.equal(editor.data.jobs.length,0);editor.configure({ownerIds:'999'});await worker.ingest({update_id:2,business_message:message()});assert.equal(editor.data.jobs.length,0);});
test('chat filters and per-day limit only affect editor',async t=>{const {worker,editor}=fixture(t);editor.configure({chatMode:'allow',chatIds:'888',excludeChatIds:'888'});await worker.ingest({update_id:1,business_message:message()});assert.equal(editor.data.jobs.length,0);editor.configure({excludeChatIds:'',dailyLimit:1});for(let id=1;id<=2;id++)await worker.ingest({update_id:id,business_message:message({message_id:id})});assert.deepEqual(editor.data.jobs.map(j=>j.status),['pending','skipped']);});
test('duplicate deliveries and bot edit updates never reprocess',async t=>{const {worker,editor,calls}=fixture(t);const update={update_id:1,business_message:message()};await worker.ingest(update);await worker.ingest(update);assert.equal(editor.data.jobs.length,1);await editor.process(editor.data.jobs[0]);const result=calls.find(x=>x.method==='editMessageText').body;await worker.ingest({update_id:2,edited_business_message:message({text:result.text})});await worker.ingest(update);assert.equal(editor.data.jobs.length,1);assert.equal(editor.data.jobs[0].status,'done');});
test('manual edit or deletion during AI processing cancels delivery',async t=>{for(const event of ['edit','delete']){let release,started;const ready=new Promise(r=>started=r);const {worker,editor,calls}=fixture(t,{editorFormat:text=>{started();return new Promise(r=>release=()=>r(text+'!'));}});await worker.ingest({update_id:1,business_message:message()});const work=editor.process(editor.data.jobs[0]);await ready;await worker.ingest({update_id:2,...(event==='edit'?{edited_business_message:message({text:'сам исправил'})}:{deleted_business_messages:{business_connection_id:'business',chat:{id:888},message_ids:[10]}})});release();await work;assert.equal(editor.data.jobs[0].status,'cancelled');assert.ok(!calls.some(c=>c.method==='editMessageText'));}});
test('disabling or changing owners during processing cancels pending edit',async t=>{let release,started;const ready=new Promise(r=>started=r);const {worker,editor,calls}=fixture(t,{editorFormat:text=>{started();return new Promise(r=>release=()=>r(text+'!'));}});await worker.ingest({update_id:1,business_message:message()});const work=editor.process(editor.data.jobs[0]);await ready;editor.configure({enabled:false});release();await work;assert.equal(editor.data.jobs[0].status,'cancelled');assert.ok(!calls.some(c=>c.method==='editMessageText'));});
test('connection rights are refreshed before editing',async t=>{const {worker,editor}=fixture(t,{telegram:async method=>{assert.equal(method,'getBusinessConnection');return {...conn,rights:{can_reply:false}};}});await worker.ingest({update_id:1,business_message:message()});await editor.process(editor.data.jobs[0]);assert.equal(editor.data.jobs[0].status,'cancelled');});
test('timeout does not replay a possibly applied edit',async t=>{const {worker,editor}=fixture(t,{telegram:async method=>{if(method==='getBusinessConnection')return conn;throw Error('timeout');}});await worker.ingest({update_id:1,business_message:message()});await editor.process(editor.data.jobs[0]);assert.equal(editor.data.jobs[0].status,'uncertain');assert.equal(editor.data.jobs[0].message,undefined);});
test('model failure leaves original message and erases stored payload',async t=>{const {worker,editor,calls}=fixture(t,{editorFormat:async()=>{throw Error('OpenAI unavailable');}});await worker.ingest({update_id:1,business_message:message()});await editor.process(editor.data.jobs[0]);assert.equal(editor.data.jobs[0].status,'failed');assert.equal(editor.data.jobs[0].message,undefined);assert.ok(!calls.some(c=>c.method==='editMessageText'));});
test('restart cancels old jobs and stored message text is encrypted',async t=>{const {worker,editor,store}=fixture(t);await worker.ingest({update_id:1,business_message:message()});assert.ok(!fs.readFileSync(editor.file,'utf8').includes(message().text));assert.ok(!JSON.stringify(editor.status()).includes(message().text));const next=new Worker(store);assert.equal(next.editor.data.jobs[0].status,'cancelled');assert.equal(next.editor.data.jobs[0].message,undefined);});
test('emoji, UTF-16 offsets, protected links and code round-trip correctly',()=>{const text='Привет 👋 зайди сюда и выполни npm run test за 10 минут';const entities=[{type:'text_link',offset:text.indexOf('сюда'),length:4,url:'https://example.com/a?token=x'},{type:'code',offset:text.indexOf('npm'),length:12}];const p=protect(text,entities);const r=restore('**Шаги**\n'+p.input,p,true);assert.equal(r.text,'Шаги\n'+text);for(const e of entities)assert.ok(r.entities.some(x=>x.type===e.type&&x.offset===e.offset+5&&x.length===e.length));assert.ok(!p.input.includes('npm run test'));assert.ok(!p.input.includes('10'));});
test('changed, duplicated protected data and oversized output are rejected',()=>{const p=protect('Открой https://example.com и введи 42');assert.throws(()=>restore(p.input.replace(p.tokens[0].marker,''),p,true));assert.throws(()=>restore(p.input+p.tokens[0].marker,p,true));assert.throws(()=>restore('x'.repeat(4097),protect('plain'),true));});
test('settings and prompt enforce selected formatting controls',()=>{assert.throws(()=>validate({enabled:true}));assert.throws(()=>validate({ownerIds:'oops'}));assert.throws(()=>validate({minLength:0}));const c=validate({enabled:true,ownerIds:'777',emoji:true,emojiPlacement:'inline',emojiDensity:'expressive'});const prompt=instructions(c);assert.match(prompt,/внутри текста/);assert.match(prompt,/нумерованными шагами/);assert.match(instructions({...c,emoji:false,lists:false}),/Не добавляй новых эмодзи/);assert.equal(defaults.enabled,false);});
test('editor authenticated API preview cannot enable processing or modify voice config',async t=>{const {store,worker,editor}=fixture(t);const server=createServer(store,worker,'secret');server.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));t.after(()=>server.close());const base='http://127.0.0.1:'+server.address().port;assert.equal((await fetch(base+'/api/editor')).status,401);const before=JSON.stringify(store.data.config),editorBefore=JSON.stringify(editor.data.config);const r=await fetch(base+'/api/editor/preview',{method:'POST',headers:{'x-admin-token':'secret','Content-Type':'application/json'},body:JSON.stringify({text:'сначала открой настройки потом выбери профиль',settings:{enabled:true,ownerIds:'888',emoji:false,openaiKey:'injected'}})});assert.equal(r.status,200);assert.match((await r.json()).text,/Инструкция/);assert.equal(JSON.stringify(store.data.config),before);assert.equal(JSON.stringify(editor.data.config),editorBefore);});
test('editor proxy denies ordinary operators before reaching service',async t=>{const express=require('express'),{createEditorProxy}=require('../src/editor-proxy');const app=express();app.use('/editor',createEditorProxy({authorize:token=>({authenticated:!!token,canManageSettings:false})}));const s=app.listen(0,'127.0.0.1');await new Promise(r=>s.once('listening',r));t.after(()=>s.close());const url='http://127.0.0.1:'+s.address().port+'/editor';assert.equal((await fetch(url)).status,401);assert.equal((await fetch(url,{headers:{'x-admin-token':'operator'}})).status,403);});
test('out-of-order manual edit or deletion prevents processing a late original',async t=>{for(const event of ['edit','delete']){const {worker,editor}=fixture(t);await worker.ingest({update_id:2,...(event==='edit'?{edited_business_message:message({text:'уже исправлено'})}:{deleted_business_messages:{business_connection_id:'business',chat:{id:888},message_ids:[10]}})});await worker.ingest({update_id:1,business_message:message()});assert.equal(editor.data.jobs.length,1);assert.equal(editor.data.jobs[0].status,'cancelled');}});
test('nested existing entities do not create overlapping generated bold',()=>{const text='нажми настройки';const p=protect(text,[{type:'bold',offset:6,length:9}]);const r=restore('**'+p.input+'**',p,true);assert.equal(r.entities.length,1);assert.equal(r.entities[0].offset,6);});
test('disabling during an already dispatched edit reports uncertainty honestly',async t=>{let release,started;const ready=new Promise(r=>started=r);const {worker,editor}=fixture(t,{telegram:async method=>{if(method==='getBusinessConnection')return conn;started();return new Promise(r=>release=r);}});await worker.ingest({update_id:1,business_message:message()});const work=editor.process(editor.data.jobs[0]);await ready;editor.configure({enabled:false});release(true);await work;assert.equal(editor.data.jobs[0].status,'uncertain');assert.match(editor.data.jobs[0].error,/уже передана/);});
test('explicit instruction style is available and sequential explanation gets mandatory step layout',async()=>{const {format}=require('../tools/voice/editor/format');const c=validate({style:'instruction'});assert.match(instructions(c),/нумерованные шаги/);let body;await format({store:{data:{config:{openaiKey:'fixture'}}},adapters:{},request:async(_url,options)=>{body=JSON.parse(options.body);return {ok:true,json:async()=>({status:'completed',output:[{content:[{type:'output_text',text:'1. Открой настройки.\n2. Выбери профиль.'}]}]})};}},'сначала открой настройки потом выбери профиль',[],{...defaults});assert.match(body.instructions,/Для ЭТОГО сообщения обязательно/);assert.equal(body.store,false);});
