const {test}=require('node:test');const assert=require('node:assert/strict');const vm=require('node:vm');const fs=require('node:fs');
const source=fs.readFileSync(__dirname+'/../tools/lampac/playback-client.js','utf8');
function fixture(activity={}){let now=100000;const listeners={},sent=[],timers=[];let playerData={title:'Film',url:'https://media.example.org/path?token=SECRET',torrent_hash:'a'.repeat(40)};
const v={tagName:'VIDEO',currentTime:20,duration:120,paused:false,buffered:{length:1,start:()=>0,end:()=>35}};
const follow=(name,fn)=>listeners[name]=fn;const context={Date:{now:()=>now},Math,isFinite,Lampa:{Activity:{active:()=>activity},Player:{listener:{follow},opened:()=>false,playdata:()=>playerData},PlayerVideo:{listener:{follow},video:()=>v}},document:{addEventListener(){},createElement(){return {set href(value){const u=new URL(value);this.hostname=u.hostname;this.protocol=u.protocol;}};}},setInterval(fn){timers.push(fn);}};
context.window={addEventListener(){}};vm.runInNewContext(source,context);context.window.createWorkspacePlayback({token:()=> 'token',access(){},request(action,body,done){sent.push(JSON.parse(JSON.stringify(body)));done(200,{enabled:true});}});
return{sent,v,event(name,arg){now+=3000;listeners[name](arg)},tick(){now+=10000;timers[0]()},playerData};}
test('reports playback without sending URL credentials; seconds are buffered ahead',()=>{const f=fixture();f.event('start',f.playerData);f.event('timeupdate');const d=f.sent.at(-1).playback;assert.equal(d.state,'playing');assert.equal(d.source,'media.example.org');assert.equal(d.buffer,15);assert.equal(d.position,20);assert.ok(!JSON.stringify(f.sent).includes('SECRET'));});
test('pause, decode error, stop and idle heartbeat remain observable',()=>{const f=fixture();f.tick();assert.equal(f.sent.at(-1).playback.state,'idle');f.event('start',f.playerData);f.event('pause');assert.equal(f.sent.at(-1).playback.state,'paused');f.v.error={code:3};f.event('error');assert.equal(f.sent.at(-1).playback.error,'decode');f.event('destroy');f.tick();assert.equal(f.sent.at(-1).playback.state,'ended');assert.equal(f.sent.at(-1).playback.error,'decode');});

test('poster is taken from the movie card and reset between films',()=>{const f=fixture();f.event('start',{...f.playerData,card:{poster_path:'/poster_123.jpg'}});assert.equal(f.sent.at(-1).playback.poster,'https://image.tmdb.org/t/p/w300/poster_123.jpg');f.event('start',{...f.playerData,card:{poster:'https://image.tmdb.org/t/p/original/poster_456.png'}});assert.equal(f.sent.at(-1).playback.poster,'https://image.tmdb.org/t/p/w300/poster_456.png');f.event('start',{...f.playerData,poster:'https://internal.example/image?token=SECRET'});assert.equal(f.sent.at(-1).playback.poster,'');assert.ok(!JSON.stringify(f.sent).includes('SECRET'));});

test('online player resolves movie from active activity and unwraps image proxies without credentials',()=>{const f=fixture({movie:{img:'https://lc.example.org/tmdb/https://image.tmdb.org/t/p/w500/realposter.jpg?token=SECRET'}});f.event('start',f.playerData);assert.equal(f.sent.at(-1).playback.poster,'https://image.tmdb.org/t/p/w300/realposter.jpg');assert.ok(!JSON.stringify(f.sent).includes('SECRET'));f.event('start',{...f.playerData,movie:{poster_path:'/own.jpg'}});assert.equal(f.sent.at(-1).playback.poster,'https://image.tmdb.org/t/p/w300/own.jpg');});
