(function(){'use strict';
if(window.workspaceAmbient)return;
var enabled=false,node,style,activityHook=false,playerHook=false,playing=false,queued=false;
var css='#workspace-kv9-ambient{position:fixed;top:0;right:0;bottom:0;left:0;z-index:0;pointer-events:none;overflow:hidden;background:#050B10;display:none}#workspace-kv9-ambient::before,#workspace-kv9-ambient::after{content:"";position:absolute;top:-15%;right:-15%;bottom:-15%;left:-15%;background:radial-gradient(ellipse at 25% 30%,#2ed3b72b,transparent 55%),radial-gradient(ellipse at 80% 75%,#14697938,transparent 55%);animation:workspace-kv9-drift 32s ease-in-out infinite alternate;will-change:transform}#workspace-kv9-ambient::after{animation-direction:alternate-reverse;animation-duration:43s;opacity:.6}body.workspace-kv9-ambient #workspace-kv9-ambient{display:block}body.workspace-kv9-ambient .background{visibility:hidden!important}@keyframes workspace-kv9-drift{from{transform:translate3d(-3%,-2%,0) scale(1)}to{transform:translate3d(3%,3%,0) scale(1.08)}}@media(prefers-reduced-motion:reduce){#workspace-kv9-ambient::before,#workspace-kv9-ambient::after{animation:none;will-change:auto}}';
function refresh(){if(!document.body||!window.Lampa)return;var active=Lampa.Activity&&Lampa.Activity.active?Lampa.Activity.active():null;var full=active&&active.component==='full';var show=enabled&&!full&&!playing&&!document.hidden&&!document.querySelector('.player,.youtube-player');if(document.body.classList.contains('workspace-kv9-ambient')!==!!show)document.body.classList.toggle('workspace-kv9-ambient',!!show);}
function schedule(){if(queued)return;queued=true;setTimeout(function(){queued=false;refresh();},0);}
function hooks(){if(!window.Lampa)return;if(!activityHook&&Lampa.Listener){activityHook=true;Lampa.Listener.follow('activity',schedule);}if(!playerHook&&Lampa.Player&&Lampa.Player.listener){playerHook=true;Lampa.Player.listener.follow('start',function(){playing=true;refresh();});Lampa.Player.listener.follow('destroy',function(){playing=false;schedule();});}}
window.workspaceAmbient={update:function(theme,motion){enabled=!!theme&&String(motion)!=='false';if(!node&&enabled&&document.body){style=document.createElement('style');style.id='workspace-kv9-ambient-style';style.textContent=css;document.head.appendChild(style);node=document.createElement('div');node.id='workspace-kv9-ambient';node.setAttribute('aria-hidden','true');document.body.insertBefore(node,document.body.firstChild);}hooks();refresh();},refresh:refresh};
if(typeof MutationObserver!=='undefined')new MutationObserver(schedule).observe(document.documentElement,{childList:true,subtree:true});
document.addEventListener('visibilitychange',refresh);
})();
