'use strict';
const {TelegramClient,Api,utils}=require('telegram');
const {StringSession}=require('telegram/sessions');
const {NewMessage,EditedMessage,DeletedMessage}=require('telegram/events');
function peerData(e){if(e.className==='Channel')return{kind:'channel',id:e.id.toString(),hash:e.accessHash.toString()};if(e.className==='Chat')return{kind:'chat',id:e.id.toString()};return{kind:'user',id:e.id.toString(),hash:(e.accessHash||0).toString()};}
function inputPeer(json){const p=JSON.parse(json),big=require('big-integer');return p.kind==='channel'?new Api.InputPeerChannel({channelId:big(p.id),accessHash:big(p.hash)}):p.kind==='chat'?new Api.InputPeerChat({chatId:big(p.id)}):new Api.InputPeerUser({userId:big(p.id),accessHash:big(p.hash)});}
function message(m){return{id:m.id,date:Number(m.date)*1000,sender:[m.sender?.firstName,m.sender?.lastName,m.sender?.title,m.senderId?.toString()].filter(Boolean).join(' '),body:m.message||'',reply_id:m.replyTo?.replyToMsgId||null};}
class Account{
 constructor(store){this.store=store;this.client=null;this.pending=null;this.busy=false;this.error='';this.timer=null;this.live=false;this.retryAt=0;}
 async connect(){if(this.client)return this.client;const s=this.store.state.secrets;if(!s.apiId||!s.apiHash)throw Error('Укажите API ID и API Hash');this.client=new TelegramClient(new StringSession(s.session||''),Number(s.apiId),s.apiHash,{connectionRetries:3,requestRetries:1,floodSleepThreshold:0,deviceModel:'KV9RU Workspace',appVersion:'1.0',autoReconnect:true});this.client.setLogLevel('none');try{await this.client.connect();return this.client;}catch(e){await this.client.disconnect().catch(()=>{});this.client=null;throw e;}}
 async restore(){if(!this.store.state.secrets.session)return;try{const c=await this.connect();if(!await c.checkAuthorization())throw Error('Сессия Telegram отозвана. Войдите заново.');await this.finish(await c.getMe());}catch(e){this.error=e.message;}}
 async sendCode(phone){if(this.busy||this.live)throw Error('Аккаунт уже подключён или выполняется операция');if(!/^\+\d{7,15}$/.test(phone))throw Error('Телефон в формате +79991234567');this.busy=true;try{const c=await this.connect(),r=await c.sendCode({apiId:Number(this.store.state.secrets.apiId),apiHash:this.store.state.secrets.apiHash},phone);this.pending={phone,hash:r.phoneCodeHash,at:Date.now(),twofa:false};return{stage:'code',viaApp:r.isCodeViaApp};}finally{this.busy=false;}}
 async login(code,password){if(this.busy)throw Error('Вход уже выполняется');if(!this.pending||Date.now()-this.pending.at>10*60000)throw Error('Запросите новый код');this.busy=true;try{const c=await this.connect();let user;if(this.pending.twofa){if(!password)throw Error('Введите облачный пароль Telegram');user=await c.signInWithPassword({apiId:Number(this.store.state.secrets.apiId),apiHash:this.store.state.secrets.apiHash},{password:async()=>password,onError:async e=>{throw e;}});}else{try{const r=await c.invoke(new Api.auth.SignIn({phoneNumber:this.pending.phone,phoneCodeHash:this.pending.hash,phoneCode:String(code||'').replace(/\s/g,'')}));if(!r.user)throw Error('Войдите в существующий аккаунт');user=r.user;}catch(e){if(e.errorMessage==='SESSION_PASSWORD_NEEDED'){this.pending.twofa=true;return{stage:'password'};}throw e;}}await this.finish(user);this.pending=null;return{stage:'ready'};}finally{this.busy=false;}}
 async finish(user){if(user.bot)throw Error('Нужен личный Telegram, не бот');const id=user.id.toString();if(this.store.state.ownerId&&this.store.state.ownerId!==id){await this.client.disconnect();this.client=null;throw Error('База принадлежит другому аккаунту. Подключите прежний аккаунт.');}Object.assign(this.store.state,{ownerId:id,account:[user.firstName,user.lastName].filter(Boolean).join(' ')});this.store.state.secrets.session=this.client.session.save();this.store.save();this.live=true;this.error='';this.attach();}
 attach(){if(this.attached)return;this.attached=true;const ingest=async event=>{try{if(!this.store.state.config.enabled||!this.hasSpace())return;const id=event.chatId?.toString(),c=this.store.db.prepare('SELECT selected FROM chats WHERE id=?').get(id);if(c?.selected)this.store.putMessages(id,[message(event.message)]);}catch{this.error='Не удалось сохранить обновление Telegram';}};this.client.addEventHandler(ingest,new NewMessage({}));this.client.addEventHandler(ingest,new EditedMessage({}));this.client.addEventHandler(event=>{const ids=event.deletedIds||[];for(const id of ids){if(event.chatId)this.store.db.prepare('DELETE FROM messages WHERE chat_id=? AND id=?').run(event.chatId.toString(),id);else this.store.db.prepare("DELETE FROM messages WHERE id=? AND chat_id IN (SELECT id FROM chats WHERE json_extract(peer,'$.kind')!='channel')").run(id);}},new DeletedMessage({}));}
 hasSpace(){const fs=require('fs'),s=fs.statfsSync(this.store.dir);if(this.store.bytes()>this.store.state.config.maxStorageMB*1048576||s.bavail*s.bsize<512*1048576){this.error='Импорт приостановлен: достигнут лимит базы или на диске осталось менее 512 МБ';return false;}return true;}
 async dialogs(){if(!this.live)throw Error('Сначала войдите в Telegram');if(this.busy)throw Error('Telegram занят, повторите через несколько секунд');this.busy=true;try{for await(const d of this.client.iterDialogs({})){const e=d.entity;if(!e||e.deleted||!['Channel','Chat','User'].includes(e.className)||e.bot||e.id.toString()==='777000')continue;this.store.putChat({id:utils.getPeerId(e).toString(),title:d.title||d.name||'Без названия',username:e.username||'',peer:JSON.stringify(peerData(e))});}return this.store.chats();}finally{this.busy=false;}}
 async sync(){if(Date.now()<this.retryAt||this.busy||!this.live||!this.store.state.config.enabled||!this.hasSpace())return;this.busy=true;try{
  const chats=this.store.db.prepare('SELECT * FROM chats WHERE selected=1 AND next_at<=? ORDER BY updated ASC LIMIT 8').all(Date.now());
  for(const chat of chats){if(!this.store.state.config.enabled||!this.hasSpace())break;try{
   const peer=inputPeer(chat.peer);
   // Catch up from the last persisted message before continuing backwards.
   if(chat.latest){const fresh=await this.client.getMessages(peer,{limit:100,minId:chat.latest,reverse:true});if(fresh.length&&this.store.state.config.enabled&&this.store.db.prepare('SELECT selected FROM chats WHERE id=?').get(chat.id)?.selected){this.store.putMessages(chat.id,fresh.map(message));this.store.db.prepare('UPDATE chats SET latest=? WHERE id=?').run(Math.max(...fresh.map(m=>m.id),chat.latest),chat.id);}}
   if(!chat.complete){const batch=await this.client.getMessages(peer,{limit:100,offsetId:chat.cursor||0});if(!this.store.db.prepare('SELECT selected FROM chats WHERE id=?').get(chat.id)?.selected)continue;this.store.putMessages(chat.id,batch.map(message));if(batch.length)this.store.db.prepare('UPDATE chats SET cursor=?,latest=MAX(latest,?) WHERE id=?').run(Math.min(...batch.map(m=>m.id)),Math.max(...batch.map(m=>m.id)),chat.id);else this.store.db.prepare('UPDATE chats SET complete=1 WHERE id=?').run(chat.id);}
   this.store.db.prepare("UPDATE chats SET updated=?,error='',next_at=0 WHERE id=?").run(Date.now(),chat.id);
  }catch(e){const seconds=Number(e.seconds)||30;this.store.db.prepare('UPDATE chats SET error=?,next_at=?,updated=? WHERE id=?').run(e.errorMessage||'Telegram временно недоступен',Date.now()+Math.max(30,seconds)*1000,Date.now(),chat.id);if(e.seconds){this.retryAt=Date.now()+Math.max(30,seconds)*1000;break;}}}
 }finally{this.busy=false;}}
 start(){this.timer=setInterval(()=>this.sync().catch(()=>{this.error='Ошибка синхронизации';}),3000);this.timer.unref();}
 async disconnect(){if(this.busy)throw Error('Дождитесь завершения текущего пакета импорта');this.live=false;if(this.client){try{await this.client.invoke(new Api.auth.LogOut());}catch{}await this.client.disconnect();}this.client=null;this.attached=false;this.pending=null;delete this.store.state.secrets.session;this.store.state.config.enabled=false;this.store.save();}
}
module.exports={Account,message,inputPeer};
