'use strict';
// Isolated UI + editor API fixture: no real Telegram/OpenAI requests or credentials.
const assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const express=require('express'),{chromium,webkit}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const {Store}=require('../tools/voice/store'),{Worker}=require('../tools/voice/worker');
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'editor-ui-')),out=process.env.AUDIT_OUTPUT||path.join(dir,'screenshots');fs.mkdirSync(out,{recursive:true});
const store=new Store(dir,'a'.repeat(64));Object.assign(store.data.config,{botToken:'123:fixture-token-for-local-audit-only',openaiKey:'fixture-key'});store.data.connections.test={id:'test',user:{id:777,first_name:'Тестовый администратор'},is_enabled:true,rights:{can_reply:true}};
const worker=new Worker(store,{editorFormat:async text=>'**Инструкция**\n\n'+text+' ✅',telegram:async method=>method==='getMe'?{can_connect_to_business:true}:{}});
const app=express();app.get('/api/realtime/socket.io.js',(_req,res)=>res.type('js').send('window.io=()=>({on(){},emit(){},connect(){},disconnect(){},io:{on(){},opts:{}}});'));
app.use('/api/admin/editor',(req,res)=>{req.url='/api/editor'+(req.url==='/'?'':req.url);worker.editor.api(req,(code,data)=>res.status(code).json(data));});
app.use('/api',(_req,res)=>res.json({}));app.get('/admin',(_req,res)=>res.sendFile(path.resolve(__dirname,'../public/admin.html')));app.use(express.static(path.resolve(__dirname,'../public')));
(async()=>{const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));try{
 for(const [name,engine]of [['chromium',chromium],['webkit',webkit]]){const browser=await engine.launch({headless:true});try{const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());await page.goto('http://127.0.0.1:'+server.address().port+'/admin');await page.evaluate(()=>{S.token='fixture';S.permissions.canManageSettings=true;$('login').style.display='none';$('app').style.display='grid';setView('editor');});await page.locator('#editor-form').waitFor();
 for(const width of [1440,820,390]){await page.setViewportSize({width,height:960});await page.locator('#editor-subnav button').getByText('Настройки',{exact:true}).click();await page.locator('#editor details').evaluateAll(nodes=>nodes.forEach(n=>n.open=true));await page.waitForTimeout(100);assert.ok(await page.locator('#editor').evaluate(e=>e.scrollWidth<=e.clientWidth+2),name+' '+width+' overflow');await page.screenshot({path:path.join(out,`${name}-${width}-settings.png`)});
 await page.locator('[data-editor-owner="777"]').check();await page.locator('#editor-enabled').check();await page.locator('#editor-emojiDensity').selectOption('expressive');await page.getByRole('button',{name:'Сохранить настройки',exact:true}).click();await page.getByText('Сохранено',{exact:true}).waitFor();assert.equal(worker.editor.data.config.ownerIds,'777');assert.equal(worker.editor.data.config.emojiDensity,'expressive');assert.equal(store.data.config.enabled,false);
 await page.locator('#editor-subnav button').getByText('Попробовать',{exact:true}).click();await page.getByRole('button',{name:'Обработать пример',exact:true}).click();await page.getByText('Готово · в Telegram ничего не отправлено',{exact:true}).waitFor();assert.equal(await page.locator('#editor-output strong').textContent(),'Инструкция');assert.ok(await page.locator('#editor').evaluate(e=>e.scrollWidth<=e.clientWidth+2));await page.screenshot({path:path.join(out,`${name}-${width}-preview.png`)});
 await page.locator('#editor-subnav button').getByText('Журнал',{exact:true}).click();await page.getByText('Обработанных сообщений пока нет.',{exact:true}).waitFor();
 }
 assert.deepEqual(errors,[]);console.log(name+': 3 widths, account selection, settings, preview and journal passed');}finally{await browser.close();}}
 }finally{worker.stopped=true;await new Promise(r=>server.close(r));fs.rmSync(dir,{recursive:true,force:true});}})().catch(e=>{console.error(e);process.exitCode=1});
