// Local fixture server only; never connects to production.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');const assert=require('assert/strict'),fs=require('fs');
(async()=>{const b=await chromium.launch({channel:'msedge',headless:true});const p=await b.newPage({viewport:{width:1440,height:1000}});const log=[],errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>d.accept());await p.goto('http://127.0.0.1:13001/admin');await p.getByLabel('Ключ доступа',{exact:true}).fill('local-unified-admin-token');await p.getByRole('button',{name:'Войти',exact:true}).click();
async function view(id,tab){await p.locator(`.navbtn[data-view=${id}]`).click();if(tab)await p.locator(`#${id}-subnav`).getByRole('button',{name:tab,exact:true}).click();await p.waitForTimeout(100);}
async function command(selector,suffix,expected){console.log('CHECK',selector,suffix);const wait=p.waitForRequest(r=>r.method()==='POST'&&new URL(r.url()).pathname.endsWith(suffix));await p.locator(selector).first().click();const r=await wait;const data=r.postDataJSON();for(const[k,v]of Object.entries(expected||{}))assert.deepEqual(data[k],v);log.push({selector,path:new URL(r.url()).pathname,payloadKeys:Object.keys(data),passed:true});await p.waitForTimeout(200);}
await view('lampac','Сервер');await p.locator('#lampac details').evaluateAll(es=>es.forEach(e=>e.open=true));const acts=await p.locator('#lampac [data-action]').evaluateAll(es=>es.map(e=>e.dataset.action));for(const action of acts)await command(`#lampac [data-action="${action}"]`,'/action',{action});
await p.locator('#lampac details').evaluateAll(es=>es.forEach(e=>e.open=true));await command('#lc-form button.save','/configure');await p.locator('#lc-ts-load').click();await p.locator('#lc-ts-form').waitFor();await command('#lc-ts-form button[type=submit]','/torrserver');
await view('lampac','Торренты');await command('[data-drop]','/torrents',{action:'drop'});await command('[data-remove]','/torrents',{action:'rem'});
await view('lampac','Подключения');await command('[data-unblock]','/clients');await command('[data-client-block]','/clients');await p.locator('#lc-block-ip').fill('2001:db8::123');await command('#lc-block-form button','/clients');
await view('lampac','Устройства');await p.locator('[name=deviceName]').first().fill('Аудит');await command('[data-rename-form] button','/devices',{action:'rename',name:'Аудит'});await command('[data-access]','/devices',{action:'access'});await p.locator('#lampac details').evaluateAll(es=>es.forEach(e=>e.open=true));await command('[data-device-form] button.save','/devices');await command('[data-revoke]','/devices');
await view('lampac','Объявления');await p.locator('#lc-announcement-form [name=title]').fill('Аудит');await p.locator('#lc-announcement-form [name=message]').fill('Локальный тест');await command('#lc-announcement-form button.save','/devices',{action:'announce'});
await view('lampac','Источники и плагины');await p.locator('#lampac details').evaluateAll(es=>es.forEach(e=>e.open=true));await p.locator('#lc-advanced-form input[type=url]').first().fill('https://example.net');await command('#lc-advanced-form button.save','/advanced');
await view('lampac','Общие настройки');await command('#lc-client-form button.save','/client');
await view('voice','Текст и модели');await command('#voice-check','/check');await command('#voice-toggle','/configure');await p.locator('#voice details').evaluateAll(es=>es.forEach(e=>e.open=true));await command('#voice-preview-button','/preview');await command('#voice-save','/configure');await view('voice','Подключение');await p.locator('#voice details').evaluateAll(es=>es.forEach(e=>e.open=true));await command('#voice-vpn-check','/check-vpn');
await view('frp','Устройства');await p.locator('[data-edit-device]').first().click();await p.locator('#frp-device-name').fill('Audit router');await command('#frp-device-form button[type=submit]','/update-device',{name:'Audit router'});await view('frp','Подключить роутер');await p.locator('#frp-installer-name').fill('Audit installer');await p.locator('#frp-installer-password').fill('fixture-only');const download=p.waitForEvent('download');await command('#frp-generate','/generate-installer');await(await download).saveAs('work/audit-installer.bat');
assert.deepEqual(errors,[]);fs.writeFileSync('work/interface-audit/actions.json',JSON.stringify(log,null,2));console.log(log.length+' action bindings passed (local fixtures only)');await b.close();})().catch(e=>{console.error(e);process.exit(1)});
